# Generated by Django 5.2.4 on 2025-07-08 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.candidate'),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobtitle'),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='company_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_jobs', to='jobs.location'),
        ),
        migrations.AlterField(
            model_name='jobrecord',
            name='employee_residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_jobs', to='jobs.location'),
        ),
        migrations.AlterUniqueTogether(
            name='jobrecord',
            unique_together={('job_title', 'work_year', 'company_location')},
        ),
    ]
