# Generated by Django 5.2.4 on 2025-07-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
        ('jobs', '0003_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Feedbacks',
        ),
    ]
