# Generated by Django 5.2.4 on 2025-07-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_rename_feedback_feedbacks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks',
            old_name='author_name',
            new_name='author',
        ),
    ]
